server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

ingester:
  max_block_duration: 5m
  max_block_bytes: 134217728
  complete_block_timeout: 1m

compactor:
  compaction:
    block_retention: 48h
    max_block_bytes: 134217728

storage:
  trace:
    backend: local
    blocklist_poll: 30s
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/traces
